package com.tailbait.data.database.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey



/**
 * Entity representing a stalking detection alert generated by the detection algorithm.
 *
 * This entity stores alerts that are generated when the detection algorithm identifies
 * suspicious device patterns. Each alert includes severity level, involved devices and
 * locations (stored as JSON arrays), threat score, and dismissal state.
 *
 * Multiple indices are maintained for efficient filtering and querying of alerts by
 * timestamp, severity level, and dismissal status.
 *
 * @property id Auto-generated primary key for this alert record
 * @property alertLevel Severity level of the alert ("LOW", "MEDIUM", "HIGH", "CRITICAL")
 * @property title Short title summarizing the alert
 * @property message Detailed alert message describing the detection
 * @property timestamp Timestamp in milliseconds when the alert was generated
 * @property deviceAddresses JSON array of device MAC addresses involved in this alert
 * @property locationIds JSON array of location IDs where suspicious activity was detected
 * @property threatScore Calculated threat score ranging from 0.0 (no threat) to 1.0 (critical threat)
 * @property detectionDetails JSON object containing detailed detection analysis information
 * @property isDismissed Flag indicating if the user has dismissed this alert
 * @property dismissedAt Timestamp in milliseconds when the alert was dismissed (null if not dismissed)
 * @property createdAt Timestamp in milliseconds when this database record was created
 */
@Entity(
    tableName = "alert_history",
    indices = [
        Index(value = ["timestamp"]),
        Index(value = ["alert_level"]),
        Index(value = ["is_dismissed"])
    ]
)

data class AlertHistory(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    @ColumnInfo(name = "alert_level")
    val alertLevel: String,

    @ColumnInfo(name = "title")
    val title: String,

    @ColumnInfo(name = "message")
    val message: String,

    @ColumnInfo(name = "timestamp")
    val timestamp: Long,

    @ColumnInfo(name = "device_addresses")
    val deviceAddresses: String,

    @ColumnInfo(name = "location_ids")
    val locationIds: String,

    @ColumnInfo(name = "threat_score")
    val threatScore: Double,

    @ColumnInfo(name = "detection_details")
    val detectionDetails: String,

    @ColumnInfo(name = "is_dismissed")
    val isDismissed: Boolean = false,

    @ColumnInfo(name = "dismissed_at")
    val dismissedAt: Long? = null,

    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis()
)
